apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: managed-cluster
  region: us-west-2

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.micro
    minSize: 3
    maxSize: 5
    volumeSize: 10
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

  # - name: managed-ng-2
  #   instanceType: t2.large
  #   minSize: 1
  #   maxSize: 3
  # - name: ng-1
  #   instanceType: t2.small
  #   minSize: 1
  #   ssh:
  #     allow: true
  # - name: ng-2
  #   minSize: 1
  #   maxSize: 3
  #   ssh:
  #     allow: true
  #   instancesDistribution:
  #     instanceTypes: ["t2.medium"] # At least one instance type should be specified
  #     onDemandBaseCapacity: 0
  #     onDemandPercentageAboveBaseCapacity: 50
  #     spotInstancePools: 2
  # - name: ng-1
  #   instanceType: t2.micro
  #   desiredCapacity: 1
  #   ssh:
  #     allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  # - name: ng-2
  #   instanceType: t2.micro
  #   desiredCapacity: 1
  #   ssh:
  #     publicKeyPath: /Users/rbhar1/.ssh/id_rsa.pub
